function c = uitablecontroller(opts)
%UI Table Controller
%   Binds table data with UI elements
%   Documentation is under development, please examine examples: uiexample
%
%   Example app: uireactivetableExample
arguments
    opts.Data = []
    opts.DataObject = []
    opts.DataProperty (1,1) string = missing
    opts.DataReadFcn = []
    opts.DataWriteFcn = []
    opts.DataUI = []
    opts.Selection = []
    opts.SelectionObject = []
    opts.SelectionProperty (1,1) string = missing
    opts.SelectionReadFcn = []
    opts.SelectionWriteFcn = []
    opts.SelectionUI = []
    opts.Value = []
    opts.ValueObject = []
    opts.ValueProperty (1,1) string = missing
    opts.ValueReadFcn = []
    opts.ValueWriteFcn = []
    opts.ValueUI = []
end
c = UI.UITableController( ...
    Data=opts.Data, ...
    DataObject=opts.DataObject, DataProperty=opts.DataProperty, ...
    DataReadFcn=opts.DataReadFcn, DataWriteFcn = opts.DataWriteFcn, ...
    DataUI=opts.DataUI, ...
    Selection=opts.Selection, ...
    SelectionObject=opts.SelectionObject, SelectionProperty=opts.SelectionProperty, ...
    SelectionReadFcn=opts.SelectionReadFcn, SelectionWriteFcn = opts.SelectionWriteFcn, ...
    SelectionUI=opts.SelectionUI, ...
    Value=opts.Value, ...
    ValueObject=opts.ValueObject, ValueProperty=opts.ValueProperty, ...
    ValueReadFcn=opts.ValueReadFcn, ValueWriteFcn = opts.ValueWriteFcn, ...
    ValueUI=opts.ValueUI ...
    );
